site_name: GetBlobs Docs
site_url: https://naws-ai.github.io/getblobs-docs/
theme: readthedocs

nav:
  - 'GetBlobs Overview': 'index.md'
  - 'Introduction':
    - 'Core Features': 'introduction/core-features.md'
    - 'Support Tokens': 'introduction/support-tokens.md'
  - 'Guide':
    - 'Creators Guide': 'guide/creators-guide.md'
    - 'Email Login Guide': 'guide/email-login-guide.md'
    - 'Wallet Login Guide': 'guide/wallet-login-guide.md'
    - 'Buyers Guide': 'guide/buyers-guide.md'
  - 'Terms & Policies':
    - 'Terms of Service': 'terms-and-policies/terms-of-service.md'
    - 'Privacy Policy': 'terms-and-policies/privacy-policy.md'
  - 'Help Center':
    - 'FAQs': 'help-center/faqs.md'
    - 'Contact Us': 'help-center/contact-us.md'
  - 'News':
    - 'The Explore feature is being launched': 'news/the-explore-feature-is-being-launched.md'

extra_css:
  - styles/website.css
